### ISSUE TITLE
Sounder character limitation

### ISSUE THREAD

**Issue by Noitarud** [eoineoineoin/ecwt#13]
I will compliment you on the sounder idea, there's practicing and learning but hearing it in tones gives it a new feel, like a voice.

I have other characters on my keyboard that common Morse covers yet do not sound when entered, such as the period. Image given for convenience.

![morse-sec001a4](https://user-images.githubusercontent.com/98794719/234262993-c1ed9723-6069-4300-894e-0ddf782e8e58.gif)

**Comment by eoineoineoin** [comment]
Hi, glad you like it!

I can certainly add the missing symbols, but it should already handle period (the full list of symbols it knows how to sound can be seen here: https://github.com/eoineoineoin/ecwt/blob/master/app/src/main/java/es/eoinrul/ecwt/DitDahGenerator.kt#L29) - I wonder why period doesn't work for you - what language is your keyboard in? Do you use a custom keyboard app?

**Comment by Noitarud** [comment]
Perhaps I should have explored the bug a little. I use Anysoft.
I pressed the sequence as shown at top right and did not sound for the apostrophe, then I pressed the other keys and apparently it has backed up. I switched away from app and back and it began of itself to continue to sound the letters I had put in but stopped with the "a" remaining, again a switch away and return and it finished. Yes it does not want to sound apostrophe or comma.
![Screenshot_20230427-101719](https://user-images.githubusercontent.com/98794719/234729981-c014b34a-460f-464f-886a-d404aed582bb.png)

**Comment by eoineoineoin** [comment]
OK, you found a bug where the sounder stopped sending updates after an unknown character was typed in. I've fixed that and also added missing symbols, so you should see this once the app update hit the stores (usually takes a few days.) Thanks for the report!

**Comment by Noitarud** [comment]
On the subject of more characters
https://morsecode.world/international/morse.html
