### ISSUE TITLE
Add pt_BR strings

### ISSUE THREAD

**Issue by ghost** [eoineoineoin/ecwt#2]
Hello dev,

I translated strings into pt_BR.

File:
[strings](https://github.com/aevw/RD-pt_BR/blob/master/m-trainer.xml)

Thanks

**Comment by eoineoineoin** [comment]
Thanks for that.

Do you think it is also useful to add training exercises for accented characters?
According to [Wikipedia](https://en.wikipedia.org/wiki/Morse_code#Letters,_numbers,_punctuation,_prosigns_for_Morse_code_and_non-English_variants) there are some listed, but I'm not sure if those characters are transmitted, in practice? Notably, the list at that link doesn't have all the required accents -- there's no a acute or o circumflex, for example.

**Comment by ghost** [comment]
You're welcome.

For now I believe it's very good to get started with Morse, no doubt someone will request it in future.
