### ISSUE TITLE
scoring is stuck

### ISSUE THREAD

**Issue by teslasmoustache** [eoineoineoin/ecwt#3]
It's entirely possible I'm just misunderstanding how this works. But I have done multiple levels, over and over, and even slowed the effective wpm way down so that i'm *pretty sure* i'm not making any mistakes. (Although I am very new at this, tbf)

But the score stays stuck at 84%, 19 mistakes.

**Comment by eoineoineoin** [comment]
Resolving this one. There was some confusion about whether spaces should count; new post-lesson visualization should help with that in the future.
