### ISSUE TITLE
Sounder does not work with bluetooth keyboard

### ISSUE THREAD

**Issue by LiberationFrequency** [eoineoineoin/ecwt#6]
Hello, 
the Koch Training works perfectly with my bluetooth keyboard on Android 10, but the Sounder does not work. There is no screen keyboard and no external keyboard available.

**Comment by eoineoineoin** [comment]
Thanks for the report. The keyboard was tricky to get working in the sounder, so I've probably missed something. I'll get a bluetooth keyboard to test with.
