### ISSUE TITLE
Error count bug

### ISSUE THREAD

**Issue by cvlc12** [eoineoineoin/ecwt#8]
Hi

Thanks for your fun app. 

I've noticed that if you answer nothing at all with standard settings, the app shows 119 errors. Shouldn't it be an even number? 

![Screenshot_20220513-090626](https://user-images.githubusercontent.com/97767846/168252694-056cc679-cd8d-43c9-b291-9f245b62740a.png)

**Comment by eoineoineoin** [comment]
Hey, glad you're enjoying it! I think the error count is correct; it's counting the spaces between the words, too, so, with 20 words at the default settings, you'll expect to get 20 * 5 + 19 = 119 errors as a result if there were no correct guesses.

I'd like to make this a bit more obvious if I could but I'm not sure what kind of improvements we could make to this result display. Open to any suggestions.

**Comment by eoineoineoin** [comment]
Closing this off; c6b9a8b has added a tooltip if user has entered no spaces, which should reduce confusion here.
